# The URL the site will be built for
base_url = "https://dbthreee.github.io/zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = 'after-dark'

title = 'dbthreee site with zola'

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
# Put all your custom variables here
after_dark_title = "dbthreee blog with zola"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://google.com", name = "Google"},
]
